# ports del GPIO on estan connects les diferents entrades i sortides
porta:
  nom: 'Porta'
  port_finaldelinia_obert: 0
  port_finaldelinia_tancat: 0
  port_actuador_obrir: 0
  port_actuador_tancar: 0
pisto:
  nom: 'Pistó'
  port_finaldelinia_obert: 0
  port_finaldelinia_tancat: 0
  port_actuador_obrir: 0
  port_actuador_tancar: 0
premsa:
  nom: 'Premsa'
  port_finaldelinia_obert: 0
  port_finaldelinia_tancat: 0
  port_actuador_obrir: 0
  port_actuador_tancar: 0
alimentador:
  nom: 'Alimentador'
  port_finaldelinia_obert: 0
  port_finaldelinia_tancat: 0
  port_actuador_obrir: 0
  port_actuador_tancar: 0